---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leonardo@agilework.info
  namespace: application1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: User
  name: leonardo@agilework.info
