---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  annotations:
    configmanagement.gke.io/namespace-selector: prod-selector
spec:
  hard:
    cpu: "2"
    memory: 4Gi
    pods: "5"
